### ISSUE TITLE
Add scanning for assignment expressions (PEP 572)

### ISSUE THREAD

**Issue by gappleto97** [PyCQA/prospector#259]
Many developers have expressed opposition to this PEP, including a desire to ban this syntax from their projects. If there was a flag to scan for this syntax and register it as an error, this would facilitate them being able to do so.

I would prefer it if that were a default option that they had to explicitly disable,

In addition, scanning for this at a top level should be enabled by default. The following, for instance, should always be an error regardless of the flag:

```python
a = 3  # no error
b := 4  # error, doesn't need to be at top level
c = d := 5  # error, can be done better with chained assignment
```

**Comment by carlio** [comment]
Since this does not appear to have actually made it into python yet, it will be hard to use the AST functionality of astroid to be able to even detect it. Additionally, prospector is just a group of other tools so one of those is where this check would need to go. 

Also I kind of like the PEP but that has nothing to do with it :-)   prospector doesn't check anything itself but relies on other libraries to do the checking so this is not very relevant, though feel free to create a pylint-plugin or new tool or whatever else to add to prospector as a dependency if other tools that are already included do not add this.
