### ISSUE TITLE
ALE highlight doesnt show warnings.

### ISSUE THREAD

**Issue by drozdowsky** [PyCQA/prospector#301]
As I described in the title, ALE - (vim plugin) treats every message from prospector as error.
I think it is because prospector doesn't pass anything as type: 'Error'/'Warning' in output. Is there any option to output type of message?

**Comment by chocoelho** [comment]
I recall implementing `propector` support to ALE, and, AFAICR, defining what's error/warning was up to the tool rather than prospector. We already provide the codes that the wrapped tools give us as-is. Closing because this should be handled through ALE, instead of prospector. Feel free to reopen this in case you think otherwise.
