### ISSUE TITLE
six still used in tests/test_formatter.py and poetry.lock even though Py2 support has been deprecated

### ISSUE THREAD

**Issue by hjoukl** [PyCQA/prospector#476]
Running tests with tox produces `ImportError` due to six still being used in `test_formatter.py` (both `master` and current `develop`): See https://github.com/PyCQA/prospector/search?q=six.

(I admit I haven't used poetry to set up a dev venv due to lack of poetry chops; six seems to show up in the `poetry.lock` file.)

I propose removing six from both test code and the lock file since it's become superfluous.

**Comment by carlio** [comment]
You're right that it should be removed from the `test_formatter.py`, that's just an old compatibility that was left behind. 

For the lock file, that's automatically generated by poetry, and in this case the `six` dependency is declared by `coverage`. So fixing prospector is a good plan so that six is gone from there, but we can't do anything about dependencies still needing six.

Therefore the solution is just to remove it from `test_formatter.py` and not mind that it's in the lockfile because it's only used by a dependency - and a dependency that is only used in CI too.

**Comment by carlio** [comment]
`six` has been removed from the prospector code. It's still in the `poetry.lock` file however as it's a dependency of coverage, so but it won't affect running prospector or tests on prospector.
