### ISSUE TITLE
[BUG] Version incompatibility between direct usage of pylint-plugin-utils and indirect usage via pylint-django

### ISSUE THREAD

**Issue by adamcunnington-mlg** [PyCQA/prospector#478]
prospector 1.5.3.1 includes the following requirements:
pylint-plugin-utils=^0.6"
pylint-django=^2.4.4"

The trouble is that pylint-django 2.5.0 just got released and it pins pylint-django as follows:
[pylint-plugin-utils>=0.7](https://github.com/PyCQA/pylint-django/blob/v2.5.0/setup.py#L21)

Therefore, you cannot install prospector now without ending up with an incompatible version of pylint-plugin-utils.

You can easily replicate this by using a installation tool with proper dependency evaluation like pip-tools or poetry.

**Suggested Fix**
- Either explicitly pin prospector's dependency of pylint-django=2.4.4 (probably a good idea)
- Or Change the ^ dependency to be >= for prospector's requirement of pylint-plugin-utils (probably a bad idea)

**Comment by carlio** [comment]
Oops, sorry! `pylint-plugin-utils==0.7` was a release to fix the concurrent job support in pylint-django, otherwise things are mostly the same.

Therefore I'll bump the requirement in prospector to `^0.7` and make a bugfix release.

Let's see if tests work and if so, I'll make a `1.5.4` prospector release.

**Comment by carlio** [comment]
Drat, `pylint-plugin-utils` has `python>=3.6.2` and prospector `>=3.6.1` (both of which will go away soon since pylint itself drops 3.6 support soon).

However that means it's a bit more than a bugfix release, so I think solution here is:

* release `1.5.4` with `pylint-django = ^2.4` 
* Also release `1.6` with newer versions of both pylint django, pylint plugin utils and drop support for python 3.6.1.

**Comment by agalazis** [comment]
@carlio same issue with 0.8 now
