### ISSUE TITLE
[FEATURE REQUEST] Removal of `__main__.py` in 1.7.3

### ISSUE THREAD

**Issue by michaeltinsley** [PyCQA/prospector#496]
**Is your feature request related to a problem? Please describe.**

After having updated Prospector, calling Prospector as a module (`python3 -m prospector`), no longer worked.
Looking into this, it seems `prospector/__main__.py` has been removed.

Was there any particular reason for this? I am happy to fix this if it is wanted?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by carl-pr-ai** [comment]
I removed it while tidying things up and removing things I didn't think were used any more, I thought it was a relic of the past setuptools-based packaging. Basically it got removed because I forgot about the use case for running as a module.

If you create a PR to restore that I'll gladly merge that in!
