### ISSUE TITLE
List of all rules that prospector reports

### ISSUE THREAD

**Issue by siddhant-ti** [PyCQA/prospector#498]
**Is your feature request related to a problem? Please describe.**
Yes, I need the list of all rules that prospector will support with their code

**Describe the solution you'd like**
all rules in some format like csv or json, that anyone can refer to

**Comment by carlio** [comment]
This is not really possible, because prospector isn't a linting tool. It is a tool which runs other linters, so you need to know what each of those tools would report.

The problem here is that those tools add or remove messages between releases. 

Prospector would have to hard-code all of this information about every tool, and make it forwards and backwards compatible.

Basically it'd be impossible to keep accurate and up to date, and not every user uses every tool.

What you will need to do is collect that information from each of the tools that you run using prospector, because they are the source of truth for this information - for example, `pylint --list-msgs`
