### ISSUE TITLE
Prospector running extremely slow on my Django and FastAPI projects

### ISSUE THREAD

**Issue by avinashs2401** [PyCQA/prospector#613]
**Describe the bug** 
Prospector is taking too much time to run. It takes around 20 mins to complete.

**To Reproduce** 

1. Go to project folder
2. Run prospector - `prospector`
3. Takes more than 20 mins to complete

**Expected behavior** Liniting should be completed in few seconds

**Environment:**

- OS: macOS
- Tool: Defaults
- Prospector version: 1.9.0
- Python version - 3.11.3
- FastAPI version - 0.95.0
- Django version - 24.7

**Comment by carlio** [comment]
1. Run pylint by itself on the project and compare
2. Try adding more information because "it's slow" is not useful information. What is the project, can you share that? There could be pathalogical cases specific to your code.
3. Consider using [ruff](https://github.com/charliermarsh/ruff) instead

There's very little information to go off here, so please add some more. For comparison, prospector takes 7 seconds on a Django project I'm currently working on.

**Comment by carlio** [comment]
I'll close this as it is vague, with not enough detail and no follow up information, and as the title says, apparently only affects their project.

**Comment by avinashs2401** [comment]
I ran pylint directly. It was around 10 mins, while prospector was 15 mins. Let me try to investigate into my project little bit more and compare with some other simpler project to see if something causing the delay. 
Also, I will check our ruff. Thanks for that!
