### ISSUE TITLE
[BUG]Cannot run tool bandit as support was not installed.

### ISSUE THREAD

**Issue by ucakmak02** [PyCQA/prospector#618]
**Describe the bug** 
Cannot run tool bandit as support was not installed.

**To Reproduce**
1. Added this line to bitbucket-pipelines.yml :
`python -m pip install "prospector[with_bandit,with_vulture]" `

2. Pipeline running on Bitbucket returned this error:
`Cannot run tool bandit as support was not installed.`
`Please install by running 'pip install prospector[with_bandit]'`

3. Then I used it by giving a fixed version(previous version) and I didn't get any errors and it worked.
`python -m pip install "prospector[with_bandit,with_vulture]==1.10.0"`

**Screenshots** 

![Screenshot 2023-05-23 at 11 04 53](https://github.com/PyCQA/prospector/assets/44755506/06d88d53-eca4-4b9c-a113-67db7a43e067)

**Environment (please complete the following information):**

- Tool [bitbucket pipeline]
- Prospector version [1.10.1]
- Python version [3.9]

**Comment by volans-** [comment]
I have the same issue but I get the error about `pyroma`:

```
Cannot run tool pyroma as support was not installed.
Please install by running 'pip install prospector[with_pyroma]'
```

My `setup.py` has:

```
"prospector[with_everything]>=1.1.7"
```

The installed prospector is:
```
prospector==1.10.1
```
Version `1.10.1` is not an official release, nor mentioned in the CHANGELOG, but is present in PyPI. 

If I limit the upper version to `1.10.0` it works fine. Only version `1.10.1` seems broken.

**Comment by carlio** [comment]
Nevermind I found the problem - see a similar issue here: https://github.com/nix-community/poetry2nix/pull/702

It was already fixed - see https://github.com/PyCQA/prospector/pull/559 and https://github.com/PyCQA/prospector/pull/545

I made the 1.10.1 release from my laptop instead of using the `release` action so I used the newer poetry on my local machine.

Lesson learned ; I will release a new bugfix once the CI testing completes

**Comment by carlio** [comment]
`1.10.2` is released now with the fix, `with_bandit` and similar will work again. Sorry about that!
